AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Spring Boot Serverless
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringBootLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.luafanti.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: target/spring-boot-serverless-1.0.0-lambda-package.zip
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      AutoPublishAlias: live
      Policies: AWSLambdaBasicExecutionRole
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootServerlessApi:
    Description: API Gateway Hello endpoint for Spring Boot Lambda
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello'
    Export:
      Name: SpringBootServerlessApi
