AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Micronaut Serverless
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MicronautLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Runtime: java11
      CodeUri: target/micronaut-serverless-1.0.0.jar
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      AutoPublishAlias: live
      Policies: AWSLambdaBasicExecutionRole
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MicronautServerlessApi:
    Description: API Gateway Hello endpoint for Micronaut Lambda
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello'
    Export:
      Name: MicronautServerlessApi
